# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('oncr_id', models.CharField(max_length=20)),
                ('pdf_link', models.URLField()),
                ('photo', models.ImageField(upload_to='img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner_oncr_id', models.CharField(max_length=255, verbose_name='ONCR ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_affiliation', models.CharField(blank=True, max_length=1024, null=True)),
                ('approval_status', models.SmallIntegerField(choices=[(0, 'In asteptare'), (1, 'Aprobata'), (2, 'Responsa')], default=0)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
