# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
