# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180414_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner_oncr_id',
            field=models.CharField(help_text='Dac\u0103 nu \xee\u021bi cuno\u0219ti ONCR ID-ul, \xeentreab\u0103-\u021bi liderul sau \u0219eful de Centru Local', max_length=255, verbose_name='ONCR ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=2048, verbose_name='Intrebarea'),
        ),
    ]
